import type {
  CmsClient,
  CmsMedia,
  CmsProject,
  SiteSettings,
} from "./types";

const now = () => Date.now();

/* ---------- Settings ---------- */

export const seedSettings: SiteSettings = {
  title: "UTP Medtech Club",
  tagline:
    "We Capture. We Create. We Deliver.",
  contactEmail: "hello@utpmedtech.my",
  phone: "+60 3 0000 0000",
  address: "Universiti Teknologi PETRONAS, 32610 Seri Iskandar, Perak",
  instagramUrl: "https://instagram.com/utpmedtechclub",
  linkedinUrl: "https://www.linkedin.com/company/utp-medtech/",
  youtubeUrl: "https://youtube.com/@medtechutp",
};

/* ---------- Clients ---------- */

export const seedClients: CmsClient[] = [
  "PETRONAS",
  "UTP",
  "TM",
  "Yayasan PETRONAS",
  "MIDA",
  "MDEC",
].map((name, i) => ({
  id: `seed-client-${i}`,
  name,
  websiteUrl: "",
  logoMedia: "",
  published: true,
  order: i,
}));

/* ---------- Projects ---------- */

export const seedProjects: CmsProject[] = [
  {
    id: "seed-proj-0",
    title: "PETRONAS Leadership Excellence Program 2024",
    slug: "petronas-leadership-excellence-program-2024",
    category: "Corporate Event",
    year: "2024",
    location: "Kuala Lumpur",
    shortDesc:
      "A leadership development program bringing together participants from across PETRONAS for an impactful 3-day experience.",
    fullDesc:
      "A leadership development program bringing together participants from across PETRONAS for an impactful 3-day experience filled with knowledge sharing, networking and team building. MedTech provided full technical crew, multi-camera live production and post-event highlight coverage.",
    coverMedia: "",
    coverUrl: "/media/project-1.jpg",
    alt: "Corporate conference audience in an auditorium",
    featured: true,
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "seed-proj-1",
    title: "UTP Convocation Ceremony 2024",
    slug: "utp-convocation-ceremony-2024",
    category: "Convocation",
    year: "2024",
    location: "UTP Campus",
    shortDesc: "Graduation ceremony coverage for UTP's annual convocation.",
    fullDesc:
      "Full multi-camera coverage of UTP's 2024 convocation ceremony, including live streaming to remote audiences, photography and same-day highlight reels.",
    coverMedia: "",
    coverUrl: "/media/project-2.jpg",
    alt: "Graduation ceremony crowd in a hall",
    featured: true,
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "seed-proj-2",
    title: "Yayasan PETRONAS Excellence Awards 2024",
    slug: "yayasan-petronas-excellence-awards-2024",
    category: "Awards Night",
    year: "2024",
    location: "Kuala Lumpur",
    shortDesc: "Awards night gala coverage with full AV and broadcast support.",
    fullDesc:
      "Complete production support for the Yayasan PETRONAS Excellence Awards including stage lighting, broadcast switchers, audio engineering and cinematic highlight production.",
    coverMedia: "",
    coverUrl: "/media/project-3.jpg",
    alt: "Awards night gala audience under stage lights",
    featured: true,
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "seed-proj-3",
    title: "Sukmer Representative Council Summit 2024",
    slug: "sukmer-representative-council-summit-2024",
    category: "Corporate",
    year: "2024",
    location: "UTP Campus",
    shortDesc: "Sukmer summit event coverage.",
    fullDesc:
      "Photography and videography coverage of the Sukmer Representative Council Summit featuring keynotes, workshops and networking sessions.",
    coverMedia: "",
    coverUrl: "/media/about/sukmed-24.jpg",
    alt: "Sukmed summit event activities",
    featured: false,
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "seed-proj-4",
    title: "Kembara Raya Community Program 2024",
    slug: "kembara-raya-community-program-2024",
    category: "Community",
    year: "2024",
    location: "Perak",
    shortDesc: "Community road trip documentation and coverage.",
    fullDesc:
      "A community road trip program capturing cultural moments and community engagement across multiple stops in Perak.",
    coverMedia: "",
    coverUrl: "/media/about/kembara-raya-24.jpg",
    alt: "Kembara Raya community road trip",
    featured: false,
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "seed-proj-5",
    title: "Sony Videography Workshop",
    slug: "sony-videography-workshop",
    category: "Workshop",
    year: "2024",
    location: "UTP Campus",
    shortDesc: "Hands-on Sony camera workshop session.",
    fullDesc:
      "An immersive videography workshop led with Sony camera equipment, covering composition, lighting and workflow techniques.",
    coverMedia: "",
    coverUrl: "/media/about/sony-workshop.jpg",
    alt: "Sony camera workshop session",
    featured: false,
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "seed-proj-6",
    title: "Kaki Photo 2025",
    slug: "kaki-photo-2025",
    category: "Community",
    year: "2025",
    location: "UTP Campus",
    shortDesc: "Photography community meetup.",
    fullDesc:
      "A gathering of photography enthusiasts sharing techniques, gear and creative ideas during the Kaki Photo 2025 meetup.",
    coverMedia: "",
    coverUrl: "/media/about/kaki-photo-2025.jpg",
    alt: "Kaki Photo 2025 meetup",
    featured: false,
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "seed-proj-7",
    title: "SEA Awards 2024",
    slug: "sea-awards-2024",
    category: "Festival",
    year: "2024",
    location: "Kuala Lumpur",
    shortDesc: "SEA Awards ceremony production.",
    fullDesc:
      "Full event production support for SEA Awards 2024 including red carpet, stage show and backstage coverage.",
    coverMedia: "",
    coverUrl: "/media/about/sea-awards-2024.jpg",
    alt: "SEA Awards 2024 ceremony",
    featured: false,
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "seed-proj-8",
    title: "Cybergen 2025",
    slug: "cybergen-2025",
    category: "Workshop",
    year: "2025",
    location: "UTP Campus",
    shortDesc: "Cybergen 2025 technology event.",
    fullDesc:
      "A technology-centered workshop event featuring coding challenges, tech talks and innovative student projects.",
    coverMedia: "",
    coverUrl: "/media/about/cybergen-2025.jpg",
    alt: "Cybergen 2025 event",
    featured: false,
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "seed-proj-9",
    title: "Brother & Sister 2.0",
    slug: "brother-and-sister-2",
    category: "Live Streaming",
    year: "2024",
    location: "UTP Campus",
    shortDesc: "Live-streamed programme production.",
    fullDesc:
      "A mentorship programme live-streamed to UTP students with multi-camera switching and professional audio mixing.",
    coverMedia: "",
    coverUrl: "/media/about/brother-sister-2.jpg",
    alt: "Brother and Sister 2.0 programme",
    featured: false,
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
];

/* ---------- Built-in media ---------- */

const builtinImages: { path: string; name: string; alt: string }[] = [
  { path: "/media/hero.jpg", name: "hero.jpg", alt: "Camera crew operating professional video equipment" },
  { path: "/media/project-1.jpg", name: "project-1.jpg", alt: "Corporate conference audience" },
  { path: "/media/project-2.jpg", name: "project-2.jpg", alt: "Graduation ceremony crowd" },
  { path: "/media/project-3.jpg", name: "project-3.jpg", alt: "Awards night gala audience" },
  { path: "/media/photography.jpg", name: "photography.jpg", alt: "Professional camera lens close-up" },
  { path: "/media/videography.jpg", name: "videography.jpg", alt: "Camera operator filming" },
  { path: "/media/technical.jpg", name: "technical.jpg", alt: "Audio mixing console" },
  { path: "/media/graphic-design.jpg", name: "graphic-design.jpg", alt: "Graphic design workstation" },
  { path: "/media/streaming.jpg", name: "streaming.jpg", alt: "Live streaming control desk" },
  { path: "/media/marketing.jpg", name: "marketing.jpg", alt: "Marketing materials" },
  { path: "/media/why-crew.jpg", name: "why-crew.jpg", alt: "Camera crew on production set" },
  { path: "/media/cta-crowd.jpg", name: "cta-crowd.jpg", alt: "Concert crowd with stage lighting" },
  { path: "/media/about/about-hero.jpg", name: "about-hero.jpg", alt: "Camera crew at event setup" },
  { path: "/media/about/oweek-may-25.jpg", name: "oweek-may-25.jpg", alt: "Orientation week May 2025" },
  { path: "/media/about/sony-workshop.jpg", name: "sony-workshop.jpg", alt: "Sony camera workshop" },
  { path: "/media/about/sukmed-24.jpg", name: "sukmed-24.jpg", alt: "Sukmed 2024 event" },
  { path: "/media/about/kaki-photo-2025.jpg", name: "kaki-photo-2025.jpg", alt: "Kaki Photo 2025" },
  { path: "/media/about/kembara-raya-24.jpg", name: "kembara-raya-24.jpg", alt: "Kembara Raya 2024" },
  { path: "/media/about/sea-awards-2024.jpg", name: "sea-awards-2024.jpg", alt: "SEA Awards 2024" },
  { path: "/media/about/cybergen-2025.jpg", name: "cybergen-2025.jpg", alt: "Cybergen 2025" },
  { path: "/media/about/brother-sister-2.jpg", name: "brother-sister-2.jpg", alt: "Brother and Sister 2.0" },
  { path: "/media/about/bootcamp-2024.jpg", name: "bootcamp-2024.jpg", alt: "Bootcamp 2024" },
  { path: "/media/about/cultra-2024.jpg", name: "cultra-2024.jpg", alt: "Cultra 2024" },
  { path: "/media/portfolio/portfolio-hero.jpg", name: "portfolio-hero.jpg", alt: "Camera recording a MedTech stage production" },
  { path: "/media/contact/contact-hero.jpg", name: "contact-hero.jpg", alt: "MedTech production workstation" },
  { path: "/media/team/norkamar-faridatul.jpg", name: "norkamar-faridatul.jpg", alt: "Team portrait" },
  { path: "/media/team/ahmad-ilman.jpg", name: "ahmad-ilman.jpg", alt: "Team portrait" },
  { path: "/media/team/ahmad-ashraf.jpg", name: "ahmad-ashraf.jpg", alt: "Team portrait" },
  { path: "/media/team/aqryf-syah.jpg", name: "aqryf-syah.jpg", alt: "Team portrait" },
  { path: "/media/team/nur-hidayah.jpg", name: "nur-hidayah.jpg", alt: "Team portrait" },
  { path: "/media/team/zafira-agnia.jpg", name: "zafira-agnia.jpg", alt: "Team portrait" },
  { path: "/media/team/muzzammil-ikhwan.jpg", name: "muzzammil-ikhwan.jpg", alt: "Team portrait" },
  { path: "/media/team/zal-hasmi.jpg", name: "zal-hasmi.jpg", alt: "Team portrait" },
];

export const seedMedia: CmsMedia[] = builtinImages.map((m, i) => ({
  id: `builtin-media-${i}`,
  name: m.name,
  kind: "image" as const,
  mimeType: "image/jpeg",
  size: 0,
  url: m.path,
  uploadedAt: now(),
  builtin: true,
}));